//============================================================================
/// \file    MoveDirection.h
/// \authors Florian Bauer <florian.bauer.dev@gmail.com>
/// \date    2021-01-10
/// \brief   Definition of the MoveDirection Data Type for the SiteManager Feature
/// \note    Code generated by sila2codegenerator 0.3.3-dev
//============================================================================
#ifndef MOVEDIRECTION_H
#define MOVEDIRECTION_H

#include "SiteManager.grpc.pb.h"

/**
 * @brief Convenience type for the DataType_MoveDirection Protobuf Message
 */
struct MoveDirection {
    SiLA2::CReal X;
    SiLA2::CReal Y;
    SiLA2::CReal Z;
    SiLA2::CReal Distance;

    [[nodiscard]] sila2::de::fau::robot::sitemanager::v1::DataType_MoveDirection::MoveDirection_Struct*
    makeNestedMessage() const {
        using sila2::de::fau::robot::sitemanager::v1::DataType_MoveDirection;
        auto Result =
                new DataType_MoveDirection::MoveDirection_Struct{};
        Result->set_allocated_x(
                X.toProtoMessagePtr());
        Result->set_allocated_y(
                Y.toProtoMessagePtr());
        Result->set_allocated_z(
                Z.toProtoMessagePtr());
        Result->set_allocated_distance(
                Distance.toProtoMessagePtr());
        return Result;
    }

    /**
     * @brief Convert this convenience type to a SiLAFramework type, i.e. the
     * Protobuf Message
     *
     * @return The SiLAFramework equivalent of this type as a Protobuf Message
     */
    [[nodiscard]] sila2::de::fau::robot::sitemanager::v1::DataType_MoveDirection
    toProtoMessage() const {
        using sila2::de::fau::robot::sitemanager::v1::DataType_MoveDirection;
        auto Result = DataType_MoveDirection{};
        Result.set_allocated_movedirection(makeNestedMessage());
        return Result;
    }

    /**
     * @brief Convert this convenience type to a SiLAFramework type, i.e. the
     * Protobuf Message
     *
     * @return The SiLAFramework equivalent of this type as a Protobuf Message
     * pointer
     */
    [[nodiscard]] sila2::de::fau::robot::sitemanager::v1::DataType_MoveDirection*
    toProtoMessagePtr() const {
        using sila2::de::fau::robot::sitemanager::v1::DataType_MoveDirection;
        auto Result = new DataType_MoveDirection{};
        Result->set_allocated_movedirection(makeNestedMessage());
        return Result;
    }
};

#endif  // MOVEDIRECTION_H
