//============================================================================
/// \file    Pose.h
/// \authors Florian Bauer <florian.bauer.dev@gmail.com>
/// \date    2021-01-10
/// \brief   Definition of the Pose Data Type for the SiteManager Feature
/// \note    Code generated by sila2codegenerator 0.3.3-dev
//============================================================================
#ifndef POSE_H
#define POSE_H

#include "SiteManager.grpc.pb.h"

/**
 * @brief Convenience type for the DataType_Pose Protobuf Message
 */
struct Pose {
    SiLA2::CReal X;
    SiLA2::CReal Y;
    SiLA2::CReal Z;
    SiLA2::CReal OriX;
    SiLA2::CReal OriY;
    SiLA2::CReal OriZ;
    SiLA2::CReal OriW;

    [[nodiscard]] sila2::de::fau::robot::sitemanager::v1::DataType_Pose::Pose_Struct*
    makeNestedMessage() const {
        using sila2::de::fau::robot::sitemanager::v1::DataType_Pose;
        auto Result =
                new DataType_Pose::Pose_Struct{};
        Result->set_allocated_x(
                X.toProtoMessagePtr());
        Result->set_allocated_y(
                Y.toProtoMessagePtr());
        Result->set_allocated_z(
                Z.toProtoMessagePtr());
        Result->set_allocated_orix(
                OriX.toProtoMessagePtr());
        Result->set_allocated_oriy(
                OriY.toProtoMessagePtr());
        Result->set_allocated_oriz(
                OriZ.toProtoMessagePtr());
        Result->set_allocated_oriw(
                OriW.toProtoMessagePtr());
        return Result;
    }

    /**
     * @brief Convert this convenience type to a SiLAFramework type, i.e. the
     * Protobuf Message
     *
     * @return The SiLAFramework equivalent of this type as a Protobuf Message
     */
    [[nodiscard]] sila2::de::fau::robot::sitemanager::v1::DataType_Pose
    toProtoMessage() const {
        using sila2::de::fau::robot::sitemanager::v1::DataType_Pose;
        auto Result = DataType_Pose{};
        Result.set_allocated_pose(makeNestedMessage());
        return Result;
    }

    /**
     * @brief Convert this convenience type to a SiLAFramework type, i.e. the
     * Protobuf Message
     *
     * @return The SiLAFramework equivalent of this type as a Protobuf Message
     * pointer
     */
    [[nodiscard]] sila2::de::fau::robot::sitemanager::v1::DataType_Pose*
    toProtoMessagePtr() const {
        using sila2::de::fau::robot::sitemanager::v1::DataType_Pose;
        auto Result = new DataType_Pose{};
        Result->set_allocated_pose(makeNestedMessage());
        return Result;
    }
};

#endif  // POSE_H
