//============================================================================
/// \file    SiteManagerImpl.cpp
/// \authors Florian Bauer <florian.bauer.dev@gmail.com>
/// \date    2021-01-10
/// \brief   Declaration of the CSiteManagerImpl class
/// \note    Code generated by sila2codegenerator 0.3.3-dev
//============================================================================

#include "SiteManagerImpl.h"
#include <sila_cpp/common/logging.h>

using namespace std;
using namespace sila2::de::fau::robot::sitemanager::v1;

CSiteManagerImpl::CSiteManagerImpl(SiLA2::CSiLAServer* parent)
: CSiLAFeature{parent},
m_SetSiteCommand{this, "SetSite"},
m_DeleteSiteCommand{this, "DeleteSite"},
m_SitesProperty{this,
    {/*initial value*/}, "Sites"}
{
    m_SetSiteCommand.setExecutor(this, &CSiteManagerImpl::SetSite);
    m_DeleteSiteCommand.setExecutor(this, &CSiteManagerImpl::DeleteSite);
}

SetSite_Responses CSiteManagerImpl::SetSite(SetSiteWrapper* command) {
    const auto request = command->parameters();
    qDebug() << "Request contains:" << request;
    // TODO: Validate request parameters...

    // TODO: Write actual Command implementation logic...

    auto response = SetSite_Responses{};
    // TODO: Fill the response fields
    return response;
}

DeleteSite_Responses CSiteManagerImpl::DeleteSite(DeleteSiteWrapper* command) {
    const auto request = command->parameters();
    qDebug() << "Request contains:" << request;
    // TODO: Validate request parameters...

    // TODO: Write actual Command implementation logic...

    auto response = DeleteSite_Responses{};
    // TODO: Fill the response fields
    return response;
}
